export const alphabetPhotos: { letter: string, url: string }[] = [
    { letter: 'A', url: 'https://example.com/alphabet/A.png' },
    { letter: 'B', url: 'https://example.com/alphabet/B.png' },
    { letter: 'C', url: 'https://example.com/alphabet/C.png' },
    { letter: 'D', url: 'https://example.com/alphabet/D.png' },
    { letter: 'E', url: 'https://example.com/alphabet/E.png' },
    { letter: 'F', url: 'https://example.com/alphabet/F.png' },
    { letter: 'G', url: 'https://example.com/alphabet/G.png' },
    { letter: 'H', url: 'https://example.com/alphabet/H.png' },
    { letter: 'I', url: 'https://example.com/alphabet/I.png' },
    { letter: 'J', url: 'https://example.com/alphabet/J.png' },
    { letter: 'K', url: 'https://example.com/alphabet/K.png' },
    { letter: 'L', url: 'https://example.com/alphabet/L.png' },
    { letter: 'M', url: 'https://example.com/alphabet/M.png' },
    { letter: 'N', url: 'https://example.com/alphabet/N.png' },
    { letter: 'O', url: 'https://example.com/alphabet/O.png' },
    { letter: 'P', url: 'https://example.com/alphabet/P.png' },
    { letter: 'Q', url: 'https://example.com/alphabet/Q.png' },
    { letter: 'R', url: 'https://example.com/alphabet/R.png' },
    { letter: 'S', url: 'https://example.com/alphabet/S.png' },
    { letter: 'T', url: 'https://example.com/alphabet/T.png' },
    { letter: 'U', url: 'https://example.com/alphabet/U.png' },
    { letter: 'V', url: 'https://example.com/alphabet/V.png' },
    { letter: 'W', url: 'https://example.com/alphabet/W.png' },
    { letter: 'X', url: 'https://example.com/alphabet/X.png' },
    { letter: 'Y', url: 'https://example.com/alphabet/Y.png' },
    { letter: 'Z', url: 'https://example.com/alphabet/Z.png' },
  ];
  